-- creates the database table for storing speedtest results
CREATE TABLE IF NOT EXISTS speedtest_results (
    speedtest_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    `type` TEXT,
    `timestamp` TEXT,
    ping_jitter REAL,
    ping_latency REAL,
    ping_low REAL,
    ping_high REAL,
    download_bandwidth INTEGER,
    download_bytes INTEGER,
    download_elapsed INTEGER,
    download_latency_iqm REAL,
    download_latency_low REAL,
    download_latency_high REAL,
    download_latency_jitter REAL,
    upload_bandwidth INTEGER,
    upload_bytes INTEGER,
    upload_elapsed INTEGER,
    upload_latency_iqm REAL,
    upload_latency_low REAL,
    upload_latency_high REAL,
    upload_latency_jitter REAL,
    packetLoss REAL,
    isp TEXT,
    interface_internalIp TEXT,
    interface_name TEXT,
    interface_macAddr TEXT,
    interface_isVpn BOOLEAN,
    interface_externalIp TEXT,
    server_id INTEGER,
    server_host TEXT,
    server_port INTEGER,
    server_name TEXT,
    server_location TEXT,
    server_country TEXT,
    server_ip TEXT,
    result_id TEXT,
    result_url TEXT,
    result_persisted BOOLEAN
);
-- creates a database table for storing data associated with the weather during a given speedtest
CREATE TABLE IF NOT EXISTS weather (
    --id INTEGER PRIMARY KEY AUTOINCREMENT,
    speedtest_id INTEGER,
     -- Location Fields
    LocationName TEXT,
    Region TEXT,
    Country TEXT,
    Lat REAL,
    Lon REAL,
    TzID TEXT,
    LocaltimeEpoch INTEGER,
    Localtime TEXT,
    -- Current Fields
    LastUpdatedEpoch INTEGER,
    LastUpdated TEXT,
    TempC REAL,
    TempF REAL,
    IsDay BOOLEAN,
    -- Condition Fields
    ConditionText TEXT,
    ConditionIcon TEXT,
    ConditionCode INTEGER,
    -- Current
    -- Wind Fields
    WindMph REAL,
    WindKph REAL,
    WindDegree INTEGER,
    WindDir TEXT,
    -- Pressure Fields
    PressureMb REAL,
    PressureIn REAL,
    -- Precipitation Fields
    PrecipMm REAL,
    PrecipIn REAL,
    -- Additional Weather Fields
    Humidity INTEGER,
    Cloud INTEGER,
    FeelslikeC REAL,
    FeelslikeF REAL,
    VisKm REAL,
    VisMiles REAL,
    Uv REAL,
    GustMph REAL,
    GustKph REAL,
    -- Air Quality Fields
    Co REAL,
    No2 REAL,
    O3 REAL,
    So2 REAL,
    Pm25 REAL,
    Pm10 REAL,
    UsEpaIndex INTEGER,
    GbDefraIndex INTEGER,
    FOREIGN KEY (speedtest_id) REFERENCES speedtest_results(speedtest_id)
);